# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('holder_name', models.CharField(max_length=100)),
                ('avatar', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
