# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=350)),
                ('product_price', models.FloatField(default=0)),
                ('sku', models.CharField(max_length=255, null=True)),
                ('unit_in_stock', models.IntegerField(default=1)),
                ('discount', models.IntegerField(default=0)),
                ('category_id', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('unit_in_order', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
