# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.TextField(max_length=350),
        ),
    ]
