# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201207_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='sku',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
