# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201207_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('size', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('created_time', models.TimeField(auto_now=True)),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
