# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('review_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('comment', models.CharField(max_length=3000)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2020, 12, 7, 7, 33, 39, 867522, tzinfo=utc))),
                ('rating_level', models.IntegerField()),
                ('product_id', models.IntegerField(default=0)),
            ],
        ),
    ]
