# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='sku_avatar',
            field=models.TextField(default=''),
        ),
    ]
