# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('product_in_order', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
